import express from "express";
import path from "path";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "20mb" }));

// Lazy initializer for Gemini client to prevent startup crash if API key is missing
let aiInstance: GoogleGenAI | null = null;

function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not defined. Please set it in Settings > Secrets.");
  }
  if (!aiInstance) {
    aiInstance = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiInstance;
}

// API Health check endpoint
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", time: new Date().toISOString() });
});

// Text generation endpoint
app.post("/api/gemini/generate", async (req, res): Promise<any> => {
  try {
    const { mode, prompt, systemInstruction, history, template } = req.body;
    const client = getGeminiClient();

    let textPrompt = prompt;
    if (mode === "refine") {
      textPrompt = `Please refine the following text using the "${template || "professional"}" style:\n\n${prompt}`;
    } else if (mode === "brainstorm") {
      textPrompt = `Generate a detailed outline or brainstorming list about:\n\n${prompt}`;
    }

    // If chat history is provided, we can use chats.create or format it. 
    // Let's use simple generateContent with format or chat history if applicable.
    if (mode === "chat" && Array.isArray(history) && history.length > 0) {
      // Create chat session with instructions
      const chat = client.chats.create({
        model: "gemini-3.5-flash",
        config: {
          systemInstruction: systemInstruction || "You are a helpful and creative AI writing and image generation assistant.",
        },
        history: history.map((h: any) => ({
          role: h.role === "user" ? "user" : "model",
          parts: [{ text: h.text }],
        })),
      });

      const response = await chat.sendMessage({ message: textPrompt });
      return res.json({ text: response.text });
    }

    // Default basic generateContent
    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents: textPrompt,
      config: {
        systemInstruction: systemInstruction || "You are a helpful and creative AI writing and image generation assistant.",
      },
    });

    res.json({ text: response.text });
  } catch (error: any) {
    console.error("Gemini Generate Error:", error);
    res.status(500).json({ error: error.message || "Failed to generate text content" });
  }
});

// Image generation endpoint using gemini-2.5-flash-image
app.post("/api/gemini/image", async (req, res): Promise<any> => {
  try {
    const { prompt, aspectRatio } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required for image generation" });
    }

    const client = getGeminiClient();

    const response = await client.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: {
        parts: [
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio || "1:1",
        },
      },
    });

    let base64Image = "";
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          base64Image = part.inlineData.data;
          break;
        }
      }
    }

    if (!base64Image) {
      return res.status(500).json({ error: "No image data was generated by the model" });
    }

    res.json({ imageUrl: `data:image/png;base64,${base64Image}` });
  } catch (error: any) {
    console.error("Gemini Image Error:", error);
    res.status(500).json({ error: error.message || "Failed to generate image" });
  }
});

// Vite / Static asset handler
async function setupApp() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server is running at http://localhost:${PORT}`);
  });
}

setupApp();
